// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';

export function AskPokedex(arg1:string,arg2:string,arg3:string):Promise<void>;

export function GetTeamMember(arg1:number):Promise<domain.TeamPokemon>;

export function ListMyTeam():Promise<Array<domain.TeamPokemon>>;
