// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';

export function AnswerQuestion(arg1:string):Promise<void>;

export function MyPokemons():Promise<Array<domain.Pokemon>>;
